### PR TITLE
fix: extensions items are not of equal size

### PR DESCRIPTION
**Pull request by johnny243**
**Before:**
image

**After:**
image

### CODE REVIEW

**Review by arielsvg — APPROVED** [review]

**Comment by atmoio** [comment]
This needs to have been built/compiled into dist file. Change will not be reflected in prod code until then.

**Comment by JaspalSuri** [comment]
Added to the internal todo list and assigned to @johnny243.

**Comment by arielsvg** [comment]
(I ran a build myself afterwards)

**Comment by johnny243** [comment]
Thanks for the heads up! I've built dist files in [this commit](https://github.com/sn-extensions/extensions-manager/commit/206c1da0a4bcd2389a052863de03251b103b7335).

**Pull request merged**
