### PR TITLE
Update deps and lockfiles

### PR DESCRIPTION
**Pull request by proletarius101**
Lockfiles are out of sync. This PR fixes the issue

### CODE REVIEW

**Comment by atmoio** [comment]
Hmm should only be either a package-lock or yarn-lock, not both. We'll have @johnny243 decide once he's working in this repo.

**Comment by proletarius101** [comment]
> Hmm should only be either a package-lock or yarn-lock, not both. We'll have @johnny243 decide once he's working in this repo.

Sure. Hopefully there is only one lockfile and it's not out-of-sync

**Review by johnny243 — CHANGES_REQUESTED** [review]
@proletarius101 `yarn` is our package manager of choice, so let's remove the `package-lock.json` file

**Comment by proletarius101** [comment]
> @proletarius101 `yarn` is our package manager of choice, so let's remove the `package-lock.json` file

Done

**Review by johnny243 — APPROVED** [review]
Thanks a lot for contributing!

**Pull request merged**
